[build]
command = "npm run build"
publish = "_site"

# [[headers]]
#   for = "/styles.css"
#   [headers.values]
#     Content-Encoding = "gzip"

[context.production]
environment = { NODE_VERSION = "18.17.0" }

[context.deploy-preview]
environment = { NODE_VERSION = "18.17.0" }

[context.branch-deploy]
environment = { NODE_VERSION = "18.17.0" }
